# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-23 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fightHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fightID', models.CharField(max_length=18)),
                ('fightPlayer1', models.CharField(max_length=8)),
                ('fightPlayer2', models.CharField(max_length=8)),
                ('fightWinner', models.CharField(max_length=8)),
                ('defScore1', models.IntegerField(default=0)),
                ('defScore2', models.IntegerField(default=0)),
                ('fightServer', models.CharField(default=b'A', max_length=10)),
                ('fightTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('imgAddress', models.CharField(default=b' ', max_length=50)),
                ('fightPlayer1Blood1', models.IntegerField(default=0)),
                ('fightPlayer1Blood2', models.IntegerField(default=0)),
                ('fightPlayer2Blood1', models.IntegerField(default=0)),
                ('fightPlayer2Blood2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='fightPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerID', models.CharField(max_length=8)),
                ('playerScore', models.IntegerField(default=0)),
                ('playerServer', models.CharField(default=b'A', max_length=10)),
                ('playerLevel', models.IntegerField(default=0)),
                ('playerWinTimes', models.IntegerField(default=0)),
                ('playerFightTimes', models.IntegerField(default=0)),
                ('playerInherit', models.IntegerField(default=0)),
                ('lastUpdateTime', models.DateTimeField(auto_now=True)),
                ('playerNowState', models.CharField(default=0, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameServer', models.CharField(default=b'A', max_length=8)),
                ('gameLun', models.IntegerField(default=0)),
                ('gameNum', models.IntegerField(default=0)),
                ('gamePlayer1ID', models.CharField(default=b'', max_length=8)),
                ('gamePlayer2ID', models.CharField(default=b'', max_length=8)),
                ('gameResult', models.CharField(max_length=8)),
                ('gameTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('gameType', models.IntegerField(default=0)),
            ],
        ),
    ]
