# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-24 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggdwj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='gameID',
            field=models.CharField(default=b'0', max_length=8),
        ),
    ]
