# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-24 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggdwj', '0002_games_gameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='gameScore',
            field=models.IntegerField(default=0),
        ),
    ]
